// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUS4V1bCytwnKgrBFooNdKy7Ag8gm0aiU',
    appId: '1:8567966125:web:3859a15a39d85c6c847924',
    messagingSenderId: '8567966125',
    projectId: 'whatsapp-clone-89c8b',
    authDomain: 'whatsapp-clone-89c8b.firebaseapp.com',
    storageBucket: 'whatsapp-clone-89c8b.firebasestorage.app',
    measurementId: 'G-1D4M1EWK9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv-KC4OtKcrBcBPuir4_RlaOwjsSk_1t0',
    appId: '1:8567966125:android:8e7abf55a7335289847924',
    messagingSenderId: '8567966125',
    projectId: 'whatsapp-clone-89c8b',
    storageBucket: 'whatsapp-clone-89c8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZx2pkhrasa_ABAV13YR5wQhMqMYJTrxU',
    appId: '1:8567966125:ios:9789699203d862f9847924',
    messagingSenderId: '8567966125',
    projectId: 'whatsapp-clone-89c8b',
    storageBucket: 'whatsapp-clone-89c8b.firebasestorage.app',
    iosBundleId: 'com.example.whatappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZx2pkhrasa_ABAV13YR5wQhMqMYJTrxU',
    appId: '1:8567966125:ios:9789699203d862f9847924',
    messagingSenderId: '8567966125',
    projectId: 'whatsapp-clone-89c8b',
    storageBucket: 'whatsapp-clone-89c8b.firebasestorage.app',
    iosBundleId: 'com.example.whatappClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUS4V1bCytwnKgrBFooNdKy7Ag8gm0aiU',
    appId: '1:8567966125:web:39234b4d56d5c305847924',
    messagingSenderId: '8567966125',
    projectId: 'whatsapp-clone-89c8b',
    authDomain: 'whatsapp-clone-89c8b.firebaseapp.com',
    storageBucket: 'whatsapp-clone-89c8b.firebasestorage.app',
    measurementId: 'G-D8BRWVWE0K',
  );
}
